### ISSUE TITLE
Remove singular interface

### ISSUE THREAD

**Issue by dcousens** [common-blockchain/cb-tester#10]
Another regret.

I think we should remove the singular interfaces.
If the interface can scale to N, just assume N always.

The ambiguity right now means the [specification](https://github.com/common-blockchain/common-blockchain) seems incomplete,  and even then the actual transport (data) is always adhering to the specification, so it is something we enforce purely for this module.

Ping @common-blockchain/owners 

The good news is that this can be done with only a breaking change to those who choose.
If we remove the singular interfaces from this module,  external modules can still choose to use them,  albeit,  they won't be under the same tests.

**Comment by rubensayshi** [comment]
hmm, I thought all endpoints already are?

what I'm more curious about, why do we support N=0?

**Comment by dcousens** [comment]
> hmm, I thought all endpoints already are?

The end points are,  I'm talking about the user-facing interface (aka, `cb-http-client`)

**Comment by jprichardson** [comment]
Sorry, it's not clear what is meant by this:

> I think we should remove the singular interfaces.
If the interface can scale to N, just assume N always.

What do you mean by "interface"?

**Comment by dcousens** [comment]
``` javascript
node.addresses.summary('1D2TxwUcdYXcNLrA2B3hZ56rTXQowobJBn', ...)
node.addresses.summary(['1D2TxwUcdYXcNLrA2B3hZ56rTXQowobJBn'], ...)
```

Currently, both are valid.  I say we remove the first,  keeping only the second.

**Comment by weilu** [comment]
Why is it bad to support both? The interface is more flexible the way it is. Also, how often do you want to push out multiple transactions?

**Comment by dcousens** [comment]
@weilu in the transaction case,  we've removed the plural API.

I think you've made a good point though that we need to outline which make sense in plural, and which in singular.
