### ISSUE TITLE
Conflict with Common-blockchain >0.3.0

### ISSUE THREAD

**Issue by hyzhak** [common-blockchain/cb-tester#13]
current build of cb-tester won't work because on `npm install` you will get last version of `common-blockchain` that greater than `0.3.0` and where was replaced `summery` with `status` 
https://github.com/common-blockchain/common-blockchain/commit/a7e4ee0860317cba9219ccd495e648c816ff24f6

**Comment by dcousens** [comment]
Seems [this line](https://github.com/common-blockchain/cb-tester/blob/master/package.json#L30) is the culprit.
I'll have a look through this, I've been iterating the interface privately and will probably get around to re-hashing this all over to `0.4.0` soon enough.

**Comment by hyzhak** [comment]
@dcousens thanks! So we will have new version of https://github.com/common-blockchain/common-blockchain/releases soon. Right?

**Comment by dcousens** [comment]
@hyzhak yup,  just need to run the tests on my own repositories to ensure everything is as it should be.

**Comment by hyzhak** [comment]
@dcousens thanks! waiting for updates

**Comment by dcousens** [comment]
@hyzhak can you let me know how you go with the new released version?

**Comment by dcousens** [comment]
Released `0.2.25`, fixes a bunch of things.  Should be good for testing AFAIK.
