### ISSUE TITLE
Helloblock faucet is down

### ISSUE THREAD

**Issue by jprichardson** [common-blockchain/cb-tester#7]
Since the Helloblock faucet isn't working anymore, thoughts on replacing with either the faucet that @weilu setup or Blocktrail?

**Comment by dcousens** [comment]
@rubensayshi any further thoughts on this?  Otherwise,  lets go with the setup that @weilu had.

**Comment by dcousens** [comment]
Resolved in https://github.com/common-blockchain/cb-tester/commit/97d494c88496ba71f27d20f1988dbdc2587a8abf
