### ISSUE TITLE
Merge into cb-http-client OR rename to cb-http-client-tests

### ISSUE THREAD

**Issue by dcousens** [common-blockchain/cb-tester#8]
A custom implementation can `devDependency` the `cb-http-client` and use `cb-http-client/tests`?

Thoughts @jprichardson / @weilu ?

**Comment by weilu** [comment]
what's cb-http-client?

**Comment by dcousens** [comment]
@weilu previously known as `cb-node`,  see https://github.com/common-blockchain/cb-http-client

**Comment by dcousens** [comment]
See the discussion [here](https://github.com/common-blockchain/cb-http-client/issues/6)

**Comment by dcousens** [comment]
Rejected, no ACKS, and this is still in use by other modules.
